### ISSUE TITLE
Interest Accrued Not displaying on Dashboard

### ISSUE THREAD

**Issue by olusesi01** [yuaruel/Monivault#1]
No Interest accrued displays on the dashboard. The User has N120 at the time of submitting this issue which was loaded previous day.

However, no interest was accrued on the account yet. The dashboard shows N0.00

Username: olusesi

See screenshot below:

![image](https://user-images.githubusercontent.com/16163848/60646700-e8564780-9e33-11e9-8592-4b94c8defaf3.png)

**Comment by henryezeanya** [comment]
Issue fixed
